---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  volumeMode: Filesystem
  capacity:
    storage: 100M
  hostPath:
    path: "/data/foo-pv"
