apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-webserver
  name: my-webserver
spec:
  containers:
  - image: nginx:1.18.0
    imagePullPolicy: IfNotPresent
    name: my-webserver
  restartPolicy: Always
