apiVersion: v1
kind: Service
metadata:
  labels:
    app: deathstar-controller
  name: deathstar-controller
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deathstar-controller
  type: NodePort
